linters:
  enable:
    - staticcheck
    - gocyclo
    - gocognit
    - govet
    - errcheck

linters-settings:
  gocyclo:
    min-complexity: 10  # Минимальная цикломатическая сложность

  gocognit:
    min-complexity: 10  # Минимальная сложность по Холстеду

issues:
  exclude-rules:
    - path: _test\.go
      text: "error return value is not checked"