name: CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set ENVs
        run: make env

      - name: Build
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml down

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Set ENVs
        run: make env

      - name: Run unit tests
        run: |
          docker compose -f docker-compose.yml up -d
          docker compose -f docker-compose.yml run movies_catalog go test ./...
          docker compose -f docker-compose.yml down

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Set ENVs
        run: make env

      - name: Run integration tests
        run: |
          docker compose -f docker-compose.yml up -d
          docker compose -f docker-compose.yml run movies_catalog go test -v -shuffle on -parallel 4 -tags=integration ./internal/view
          docker compose -f docker-compose.yml down

  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-latest
    needs: integration-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Set ENVs
        run: make env

      - name: Start Docker Compose
        run: docker compose -f docker-compose.yml up -d

      - name: Run E2E tests
        run: go test -v -tags=e2e ./internal/controller/e2e
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SERVICE_PORT: 8080

      - name: Stop Docker Compose
        run: docker compose -f docker-compose.yml down
