name: CI

on:
  push:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: |
          golangci-lint run ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set ENVs
        run: make env

      - name: Build
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml down

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Set ENVs
        run: make env

      - name: Run unit tests
        run: |
          docker compose -f docker-compose.yml up -d
          docker compose -f docker-compose.yml run movies_catalog go test ./...
          docker compose -f docker-compose.yml down

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Set ENVs
        run: make env

      - name: Run integration tests
        run: |
          docker compose -f docker-compose.yml up -d
          docker compose -f docker-compose.yml run movies_catalog go test -v -shuffle on -parallel 4 -tags=integration ./internal/view
          docker compose -f docker-compose.yml down

  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-latest
    needs: integration-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Set ENVs
        run: make env

      - name: Start Docker Compose
        run: docker compose -f docker-compose.yml up -d

      - name: Run E2E tests
        run: go test -v -shuffle on -parallel 4 -tags=e2e ./internal/controller/e2e
        env:
          REGISTER_EMAIL: ${{ secrets.REGISTER_EMAIL }}
          REGISTER_PASSWORD: ${{ secrets.REGISTER_PASSWORD }}
          EMAIL_APP_PASS: ${{ secrets.EMAIL_APP_PASS }}
          EMAIL_SERVER: ${{ secrets.EMAIL_SERVER }}
          EMAIL_SERVER_NAME: ${{ secrets.EMAIL_SERVER_NAME }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME}}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT}}
          EMAIL_SENDER_APP_PASS: ${{ secrets.EMAIL_SENDER_APP_PASS}}
          CHANGE_PASS_EMAIL: ${{ secrets.CHANGE_PASS_EMAIL}}
          CHANGE_OLD_PASS: ${{ secrets.CHANGE_OLD_PASS}}
          CHANGE_NEW_PASS: ${{ secrets.CHANGE_NEW_PASS}}
          CHANGE_PASS_APP_PASS: ${{ secrets.CHANGE_PASS_APP_PASS}}
          SERVICE_PORT: 8080
          OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces
          OTEL_RESOURCE_ATTRIBUTES: "service.name=movies_catalog,service.version=0.1.0"

      - name: create-artifact
        run: curl -o log.json -X GET "http://localhost:16686/api/traces?service=movies_catalog"

      - name: Upload log as artifact
        uses: actions/upload-artifact@v3
        with:
          name: log_result
          path: log.json

      - name: Stop Docker Compose
        run: docker compose -f docker-compose.yml down
